In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression

X,y = make_regression(n_features=10,n_samples=100)
df = pd.read_csv('spam.csv')

df['new_column'] = df['Unnamed: 0'] * 2
a = 'test','tes'
b = df['Unnamed: 0'] > 1000
c = df['Unnamed: 0'] < 2000

print(df.loc[:,'new_column'])

0       1210
1       4698
2       7248
3       9370
4       4060
        ... 
5166    3036
5167     808
5168    5866
5169    2818
5170    9614
Name: new_column, Length: 5171, dtype: int64


In [3]:
data = [
    ["Alice", "Tana", "Informatique", 15],
    ["Bob", "Tana", "Math", 12],
    ["Charlie", "Majunga", "Math", 14],
    ["David", "Tana", "Informatique", 18],
    ["Eve", "Majunga", "Informatique", 13],
    ["Frank", "Tamatave", "Math", 10],
    ["Grace", "Tamatave", "Informatique", 16],
    ["Hannah", "Tana", "Math", 17],
]

df = pd.DataFrame(data, columns=["nom", "ville", "matiere", "note"])

group = df.groupby(['ville','matiere'])
print(group.sum())

                              nom  note
ville    matiere                       
Majunga  Informatique         Eve    13
         Math             Charlie    14
Tamatave Informatique       Grace    16
         Math               Frank    10
Tana     Informatique  AliceDavid    33
         Math           BobHannah    29


In [4]:
y = np.array([[1,2,3],[4,5,6]])
y_hat = np.array([[2,2,2],[2,2,2]])
b = y * (y_hat)
print(np.sum(b))

42


In [17]:
Z = np.random.randint(1,9,(10,9))
div = np.random.rand(10,1)
soft = np.exp(Z)/div

In [ ]:
A = np.array([[5],[0],[3],[3]])
B = np.array([[1,2,3]])
C = A + B
print(C)

[[5.         2.5        1.66666667]
 [0.         0.         0.        ]
 [3.         1.5        1.        ]
 [3.         1.5        1.        ]]


In [31]:
F = np.random.randint(1,99,(10,5))
F.mean(axis=0)
F.mean(axis=1)
print(F ,'\n\n\n',F.mean(axis=0),'\n\n\n',F.mean(axis=1))
print('F : ',F.shape,' mean.axis0 : ',F.mean(axis=0,keepdims=True).shape, ' mean.axis1 : ',F.mean(axis=1,keepdims=True).shape)

[[64 71 90 19 53]
 [73 58 11 46 48]
 [34 32 36 64 14]
 [46 16 37 71 87]
 [64 38 16 30 12]
 [16 68 26 22 27]
 [34 68 51  1 77]
 [77 95  8 81 97]
 [82 36 93 81 21]
 [44 43 58 84 53]] 


 [53.4 52.5 42.6 49.9 48.9] 


 [59.4 47.2 36.  51.4 32.  31.8 46.2 71.6 62.6 56.4]
F :  (10, 5)  mean.axis0 :  (1, 5)  mean.axis1 :  (10, 1)
